//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NestEntityBindingExample.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NestEntityBindingExample.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Add に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AddButton_Content {
            get {
                return ResourceManager.GetString("AddButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DeleteButton_Content {
            get {
                return ResourceManager.GetString("DeleteButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Description に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description_Label {
            get {
                return ResourceManager.GetString("Description_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Description: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayDescription_Label {
            get {
                return ResourceManager.GetString("DisplayDescription_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ID: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayId_Label {
            get {
                return ResourceManager.GetString("DisplayId_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName_Label {
            get {
                return ResourceManager.GetString("DisplayName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Id_Label {
            get {
                return ResourceManager.GetString("Id_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input Form に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InputForm_Header {
            get {
                return ResourceManager.GetString("InputForm_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///    NextEntityBindingExample に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_Title {
            get {
                return ResourceManager.GetString("MainWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Name_Label {
            get {
                return ResourceManager.GetString("Name_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Real-time Display via Data Binding に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RealTimeDisplay_Header {
            get {
                return ResourceManager.GetString("RealTimeDisplay_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ResetButton_Content {
            get {
                return ResourceManager.GetString("ResetButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User List に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UserList_Header {
            get {
                return ResourceManager.GetString("UserList_Header", resourceCulture);
            }
        }
    }
}
